Update build-aarch64.yml

diff --git a/.github/workflows/build-aarch64.yml b/.github/workflows/build-aarch64.yml
--- a/.github/workflows/build-aarch64.yml
+++ b/.github/workflows/build-aarch64.yml
@@ -119,7 +119,7 @@ jobs:
 
         export CFLAGS="-O3 -fPIC -DANDROID -D__ANDROID__=1 -Wno-int-conversion -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types"
         export CXXFLAGS="-O3 -fPIC -DANDROID -D__ANDROID__=1 -Wno-int-conversion -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types"
-        export LDFLAGS="-L$PWD/dummy_libs -lc++_shared"
+        export LDFLAGS="-L$PWD/dummy_libs"
         
         mkdir -p $SYSROOT/usr/include
         ln -s -f /usr/include/X11 $SYSROOT/usr/include/ 2>/dev/null || true
@@ -154,17 +154,13 @@ jobs:
             --with-fontconfig-include=$SYSROOT/usr/include \
             --with-native-debug-symbols=external \
             --with-debug-level=release \
-            --with-stdc++lib=dynamic \
             --build=x86_64-unknown-linux-gnu \
             CC=$TOOLCHAIN/bin/aarch64-linux-android24-clang \
-            CXX=$TOOLCHAIN/bin/aarch64-linux-android24-clang++ || \
-        error_code=$?
-        
-        if [[ "$error_code" -ne 0 ]]; then
-          echo "CONFIGURE ERROR, showing last 100 lines of config.log:"
-          tail -100 config.log
-          exit $error_code
-        fi
+            CXX=$TOOLCHAIN/bin/aarch64-linux-android24-clang++ || {
+          echo "=== CONFIGURE FAILED ==="
+          tail -n 150 config.log
+          exit 1
+        }
         
         echo "Building OpenJDK 25..."
         cd build/linux-aarch64-server-release
